[2024-04-16T10:22:13.096+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:22:13.777+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-16T10:22:13.913+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-16T10:22:13.917+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:22:14.022+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_1> on 2024-04-13 00:00:00+00:00
[2024-04-16T10:22:14.047+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:22:14.053+0000] {standard_task_runner.py:63} INFO - Started process 110 to run task
[2024-04-16T10:22:14.185+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_1', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmp6aow9t7g']
[2024-04-16T10:22:14.312+0000] {standard_task_runner.py:91} INFO - Job 215: Subtask task_1
[2024-04-16T10:22:14.784+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-13T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:22:18.618+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_one_dag_v1' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-16T10:22:18.745+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:22:23.567+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-16T10:22:23.662+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'hello ***'"]
[2024-04-16T10:22:23.845+0000] {subprocess.py:86} INFO - Output:
[2024-04-16T10:22:24.003+0000] {subprocess.py:93} INFO - hello ***
[2024-04-16T10:22:24.005+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-16T10:22:24.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:22:25.516+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_one_dag_v1, task_id=task_1, execution_date=20240413T000000, start_date=20240416T102213, end_date=20240416T102225
[2024-04-16T10:22:26.101+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:22:26.908+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:22:26.923+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
