[2024-04-16T10:36:54.082+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:36:54.469+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-03-05T00:00:00+00:00 [queued]>
[2024-04-16T10:36:54.520+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-03-05T00:00:00+00:00 [queued]>
[2024-04-16T10:36:54.522+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:36:54.603+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): sum_list_number> on 2024-03-05 00:00:00+00:00
[2024-04-16T10:36:54.635+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=540) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:36:54.652+0000] {standard_task_runner.py:63} INFO - Started process 546 to run task
[2024-04-16T10:36:54.649+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'sum_list_number', 'scheduled__2024-03-05T00:00:00+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmpubpbzezf']
[2024-04-16T10:36:54.662+0000] {standard_task_runner.py:91} INFO - Job 313: Subtask sum_list_number
[2024-04-16T10:36:54.904+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-03-05T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:36:55.222+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='sum_list_number' AIRFLOW_CTX_EXECUTION_DATE='2024-03-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-05T00:00:00+00:00'
[2024-04-16T10:36:55.228+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:36:55.336+0000] {logging_mixin.py:188} INFO - List number random : [16, 13, 18, 17, 1, 46, 9, 26, 25, 20, 46, 26, 14, 6, 10, 36, 47, 26, 46, 34, 47, 42, 20, 15, 21]
[2024-04-16T10:36:55.377+0000] {python.py:237} INFO - Done. Returned value was: 627
[2024-04-16T10:36:55.378+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:36:55.415+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=sum_list_number, execution_date=20240305T000000, start_date=20240416T103654, end_date=20240416T103655
[2024-04-16T10:36:55.460+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:36:55.501+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:36:55.504+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
