[2024-04-16T10:21:43.108+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:21:43.227+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:21:43.275+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:21:43.276+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:21:43.368+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_1> on 2024-04-09 00:00:00+00:00
[2024-04-16T10:21:43.407+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:21:43.403+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_1', 'scheduled__2024-04-09T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmpg8vjwajo']
[2024-04-16T10:21:43.408+0000] {standard_task_runner.py:63} INFO - Started process 89 to run task
[2024-04-16T10:21:43.409+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask task_1
[2024-04-16T10:21:43.605+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_1 scheduled__2024-04-09T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:21:43.982+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_one_dag_v1' AIRFLOW_CTX_TASK_ID='task_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T00:00:00+00:00'
[2024-04-16T10:21:43.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:21:44.055+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-16T10:21:44.065+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'hello ***'"]
[2024-04-16T10:21:44.100+0000] {subprocess.py:86} INFO - Output:
[2024-04-16T10:21:44.104+0000] {subprocess.py:93} INFO - hello ***
[2024-04-16T10:21:44.105+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-16T10:21:44.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:21:44.411+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_one_dag_v1, task_id=task_1, execution_date=20240409T000000, start_date=20240416T102143, end_date=20240416T102144
[2024-04-16T10:21:45.241+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:21:45.325+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:21:45.329+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
