[2024-04-16T10:35:59.062+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:35:59.307+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-04-16T10:35:59.468+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-27T00:00:00+00:00 [queued]>
[2024-04-16T10:35:59.474+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:35:59.638+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_number> on 2024-02-27 00:00:00+00:00
[2024-04-16T10:35:59.693+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'generate_random_number', 'scheduled__2024-02-27T00:00:00+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmp7zi7xy77']
[2024-04-16T10:35:59.695+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=504) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:35:59.716+0000] {standard_task_runner.py:63} INFO - Started process 520 to run task
[2024-04-16T10:35:59.713+0000] {standard_task_runner.py:91} INFO - Job 303: Subtask generate_random_number
[2024-04-16T10:36:00.346+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-02-27T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:36:01.217+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='generate_random_number' AIRFLOW_CTX_EXECUTION_DATE='2024-02-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-27T00:00:00+00:00'
[2024-04-16T10:36:01.224+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:36:01.836+0000] {python.py:237} INFO - Done. Returned value was: [23, 22, 26, 2, 32, 31, 25, 8, 6, 50, 16, 33, 4, 21, 23, 24, 17, 2, 49, 11, 16, 34, 22, 2, 17]
[2024-04-16T10:36:01.838+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:36:02.026+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=generate_random_number, execution_date=20240227T000000, start_date=20240416T103559, end_date=20240416T103602
[2024-04-16T10:36:02.284+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:36:03.069+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:36:03.084+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
