[2024-04-24T09:14:09.896+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:09.928+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:14:10.151+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:14:10.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:10.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:10.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.152 seconds
[2024-04-24T09:14:42.326+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:42.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:14:42.409+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:14:42.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:44.000+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:14:44.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 2.125 seconds
[2024-04-24T09:15:17.032+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:17.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:15:17.432+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:15:17.412+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:18.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:19.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 2.738 seconds
[2024-04-24T09:15:55.999+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:56.006+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:15:56.045+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:15:56.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:56.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:15:59.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 3.694 seconds
[2024-04-24T09:17:13.602+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:17:13.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:17:13.935+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:17:13.753+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:17:14.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:17:18.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 6.692 seconds
[2024-04-24T09:18:10.268+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:10.271+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:18:10.275+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:18:10.274+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:10.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:10.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.083 seconds
[2024-04-24T09:18:41.845+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:41.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:18:42.033+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:18:42.004+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:42.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:18:42.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.921 seconds
[2024-04-24T09:19:13.000+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:13.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:19:13.052+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:19:13.047+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:13.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:13.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.498 seconds
[2024-04-24T09:19:44.114+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:44.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:19:44.143+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:19:44.140+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:44.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:19:44.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.250 seconds
[2024-04-24T09:20:15.136+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:15.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:20:15.144+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:20:15.143+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:15.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:15.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.081 seconds
[2024-04-24T09:20:45.884+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:45.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:20:45.890+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:20:45.889+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:45.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:20:45.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.060 seconds
[2024-04-24T09:21:16.443+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:16.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:21:16.500+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:21:16.496+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:16.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:16.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.235 seconds
[2024-04-24T09:21:47.111+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:47.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:21:47.126+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:21:47.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:47.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:21:47.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.118 seconds
[2024-04-24T09:22:17.257+0000] {processor.py:161} INFO - Started process (PID=139) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:17.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:22:17.261+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:22:17.260+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:17.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:17.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.041 seconds
[2024-04-24T09:22:47.746+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:47.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:22:47.755+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:22:47.755+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:47.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:22:47.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.066 seconds
[2024-04-24T09:23:18.711+0000] {processor.py:161} INFO - Started process (PID=164) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:18.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:23:18.725+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:23:18.724+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:18.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:18.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.135 seconds
[2024-04-24T09:23:48.952+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:48.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:23:48.956+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:23:48.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:48.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:23:48.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.039 seconds
[2024-04-24T09:24:19.335+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:19.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:24:19.343+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:24:19.342+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:19.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:19.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.079 seconds
[2024-04-24T09:24:50.134+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:50.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:24:50.138+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:24:50.138+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:50.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:24:50.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.043 seconds
[2024-04-24T09:25:20.632+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:20.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:25:20.649+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:25:20.648+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:20.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:20.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.108 seconds
[2024-04-24T09:25:51.339+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:51.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:25:51.351+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:25:51.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:51.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:25:51.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.084 seconds
[2024-04-24T09:26:21.674+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:21.676+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:26:21.679+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:26:21.679+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:21.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:21.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.081 seconds
[2024-04-24T09:26:52.537+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:52.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:26:52.541+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:26:52.541+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:52.561+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:26:52.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.045 seconds
[2024-04-24T09:27:24.939+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:27:24.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:27:25.651+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:27:25.634+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:27:26.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:27:27.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 3.253 seconds
[2024-04-24T09:28:00.957+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:28:01.026+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:28:01.191+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:28:01.127+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:28:04.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:28:20.274+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-24T09:30:06.271+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:06.274+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:30:06.284+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:30:06.283+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:06.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:06.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.141 seconds
[2024-04-24T09:30:44.569+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:44.714+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:30:45.736+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:30:45.698+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:46.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:30:48.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 5.924 seconds
[2024-04-24T09:31:20.215+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:20.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:31:20.311+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:31:20.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:20.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:20.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.975 seconds
[2024-04-24T09:31:58.293+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:58.300+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:31:58.365+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:31:58.361+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:58.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:31:59.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.891 seconds
[2024-04-24T09:32:38.709+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:32:38.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:32:39.133+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:32:39.071+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:32:40.395+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:32:40.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 2.335 seconds
[2024-04-24T09:33:12.008+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:12.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:33:12.016+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:33:12.015+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:12.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:12.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.153 seconds
[2024-04-24T09:33:44.150+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:44.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:33:44.162+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:33:44.161+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:44.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:33:44.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.142 seconds
[2024-04-24T09:34:14.407+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:14.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:34:14.411+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:34:14.410+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:14.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:14.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.042 seconds
[2024-04-24T09:34:45.083+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:45.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:34:45.114+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:34:45.113+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:45.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:34:45.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.159 seconds
[2024-04-24T09:35:30.142+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:35:30.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:35:30.329+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:35:30.292+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:35:30.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:35:48.062+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-24T09:36:20.911+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:20.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:36:21.032+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:36:21.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:21.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:22.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.770 seconds
[2024-04-24T09:36:52.931+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:52.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:36:52.946+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:36:52.945+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:53.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:36:53.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.158 seconds
[2024-04-24T09:37:34.480+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:37:34.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:37:34.523+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:37:34.519+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:37:34.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:37:50.824+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-24T09:38:25.117+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:25.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:38:25.126+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:38:25.124+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:25.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:25.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.111 seconds
[2024-04-24T09:38:55.532+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:55.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:38:55.557+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:38:55.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:55.651+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:38:55.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.398 seconds
[2024-04-24T09:39:26.344+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:26.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:39:26.347+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:39:26.347+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:26.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:26.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.044 seconds
[2024-04-24T09:39:56.825+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:56.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:39:56.828+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:39:56.827+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:56.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:39:56.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.048 seconds
[2024-04-24T09:40:27.514+0000] {processor.py:161} INFO - Started process (PID=297) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:27.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:40:27.525+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:40:27.524+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:27.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:27.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.164 seconds
[2024-04-24T09:40:58.090+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:58.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:40:58.093+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:40:58.093+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:58.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:40:58.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.130 seconds
[2024-04-24T09:41:42.606+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:41:42.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:41:42.664+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:41:42.643+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:41:43.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:41:44.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.932 seconds
[2024-04-24T09:42:17.590+0000] {processor.py:161} INFO - Started process (PID=358) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:42:17.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:42:17.715+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:42:17.659+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:42:18.406+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:42:20.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 3.428 seconds
[2024-04-24T09:43:09.941+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:09.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:43:09.993+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:43:09.978+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:10.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:13.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 4.072 seconds
[2024-04-24T09:43:50.975+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:51.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:43:51.106+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:43:51.073+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:51.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:43:59.959+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 9.184 seconds
[2024-04-24T09:44:32.784+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:44:32.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:44:32.847+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:44:32.833+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:44:33.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:44:33.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.844 seconds
[2024-04-24T09:45:04.066+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:04.075+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:45:04.078+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:45:04.077+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:04.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:04.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.158 seconds
[2024-04-24T09:45:35.020+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:35.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:45:35.037+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:45:35.035+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:35.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:45:35.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.248 seconds
[2024-04-24T09:46:05.925+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:05.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:46:05.930+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:46:05.929+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:05.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:05.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.064 seconds
[2024-04-24T09:46:36.073+0000] {processor.py:161} INFO - Started process (PID=434) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:36.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:46:36.075+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:46:36.075+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:36.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:46:36.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.035 seconds
[2024-04-24T09:47:07.273+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:47:07.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:47:07.321+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:47:07.318+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:47:07.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:47:07.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.560 seconds
[2024-04-24T09:47:56.764+0000] {processor.py:161} INFO - Started process (PID=452) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:47:56.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:47:56.874+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:47:56.854+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:47:57.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:48:02.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 5.777 seconds
[2024-04-24T09:48:54.948+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:48:55.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:48:55.021+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:48:55.011+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:48:55.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:49:05.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 11.095 seconds
[2024-04-24T09:49:50.664+0000] {processor.py:161} INFO - Started process (PID=31) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:49:50.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:49:50.669+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:49:50.668+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:49:50.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:49:50.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.053 seconds
[2024-04-24T09:50:21.176+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:21.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:50:21.189+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:50:21.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:21.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:21.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.103 seconds
[2024-04-24T09:50:51.330+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:51.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:50:51.344+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:50:51.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:51.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:50:51.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.086 seconds
[2024-04-24T09:51:21.634+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:21.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:51:21.666+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:51:21.663+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:21.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:21.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.216 seconds
[2024-04-24T09:51:52.049+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:52.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:51:52.056+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:51:52.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:52.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:51:52.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.132 seconds
[2024-04-24T09:52:23.427+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:23.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:52:23.452+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:52:23.449+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:23.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:23.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.309 seconds
[2024-04-24T09:52:55.184+0000] {processor.py:161} INFO - Started process (PID=110) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:55.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:52:55.562+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:52:55.547+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:56.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:52:57.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 3.280 seconds
[2024-04-24T09:53:51.739+0000] {processor.py:161} INFO - Started process (PID=137) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:53:51.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:53:52.100+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:53:52.042+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:53:52.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:54:05.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 14.141 seconds
[2024-04-24T09:54:36.750+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:54:36.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:54:36.780+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:54:36.776+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:54:36.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:54:36.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.208 seconds
[2024-04-24T09:55:11.306+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:11.413+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:55:11.788+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:55:11.746+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:12.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:12.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.931 seconds
[2024-04-24T09:55:44.264+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:44.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:55:44.449+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:55:44.431+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:44.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:55:54.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 10.469 seconds
[2024-04-24T09:56:32.145+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:56:32.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:56:32.159+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:56:32.157+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:56:32.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:56:32.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.141 seconds
[2024-04-24T09:57:02.514+0000] {processor.py:161} INFO - Started process (PID=203) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:02.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:57:02.522+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:57:02.520+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:02.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:02.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.111 seconds
[2024-04-24T09:57:32.740+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:32.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:57:32.744+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:57:32.744+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:32.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:57:32.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.058 seconds
[2024-04-24T09:58:37.020+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:58:37.037+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:58:37.086+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:58:37.052+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:58:38.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:58:46.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 11.350 seconds
[2024-04-24T09:59:17.918+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:17.938+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:59:17.962+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:59:17.944+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:18.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:23.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 5.838 seconds
[2024-04-24T09:59:55.760+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:55.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T09:59:56.154+0000] {logging_mixin.py:188} INFO - [2024-04-24T09:59:56.097+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:56.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T09:59:56.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.928 seconds
[2024-04-24T10:00:47.146+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:00:47.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:00:47.249+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:00:47.182+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:00:47.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:00:48.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 1.123 seconds
[2024-04-24T10:01:19.165+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:19.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:01:19.184+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:01:19.183+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:19.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:19.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.213 seconds
[2024-04-24T10:01:49.471+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:49.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:01:49.475+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:01:49.474+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:49.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:01:49.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.104 seconds
[2024-04-24T10:02:20.330+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:02:20.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:02:20.340+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:02:20.339+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:02:20.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:02:20.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.423 seconds
[2024-04-24T10:02:55.956+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:02:55.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:02:55.983+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:02:55.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:02:56.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:03:00.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 9.115 seconds
[2024-04-24T10:03:30.464+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:03:30.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:03:30.468+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:03:30.466+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:03:30.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:03:30.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.059 seconds
[2024-04-24T10:04:36.376+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:04:36.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:04:36.430+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:04:36.419+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:04:37.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:04:41.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 6.222 seconds
[2024-04-24T10:05:11.921+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:11.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:05:11.925+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:05:11.924+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:11.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:11.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.042 seconds
[2024-04-24T10:05:42.706+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:42.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:05:42.709+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:05:42.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:42.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:05:42.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.045 seconds
[2024-04-24T10:06:43.339+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:06:43.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:06:43.357+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:06:43.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:06:43.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:06:44.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.867 seconds
[2024-04-24T10:07:22.107+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:07:22.116+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:07:22.138+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:07:22.126+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:07:22.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:07:32.290+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 615, in update_import_errors
    session.execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-04-24T10:08:03.025+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:03.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:08:03.028+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:08:03.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:03.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:03.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.046 seconds
[2024-04-24T10:08:33.693+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:33.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:08:33.695+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:08:33.695+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:33.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:08:33.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 0.034 seconds
[2024-04-24T10:09:04.183+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:09:04.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py for tasks to queue
[2024-04-24T10:09:04.213+0000] {logging_mixin.py:188} INFO - [2024-04-24T10:09:04.204+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:09:04.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py
[2024-04-24T10:09:11.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/custom_operator/collect_data_fruits_operator.py took 7.774 seconds
