[2024-04-16T10:36:45.098+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:36:46.199+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-04-16T10:36:46.279+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-02-28T00:00:00+00:00 [queued]>
[2024-04-16T10:36:46.283+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:36:46.406+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): sum_list_number> on 2024-02-28 00:00:00+00:00
[2024-04-16T10:36:46.477+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=533) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:36:46.492+0000] {standard_task_runner.py:63} INFO - Started process 535 to run task
[2024-04-16T10:36:46.491+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'sum_list_number', 'scheduled__2024-02-28T00:00:00+00:00', '--job-id', '307', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmpvlxtdhe6']
[2024-04-16T10:36:46.536+0000] {standard_task_runner.py:91} INFO - Job 307: Subtask sum_list_number
[2024-04-16T10:36:46.791+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.sum_list_number scheduled__2024-02-28T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:36:47.075+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='sum_list_number' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-28T00:00:00+00:00'
[2024-04-16T10:36:47.081+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:36:47.258+0000] {logging_mixin.py:188} INFO - List number random : [31, 8, 7, 31, 36, 46, 7, 34, 17, 9, 19, 14, 32, 3, 20, 24, 49, 38, 45, 41, 14, 29, 5, 16, 13]
[2024-04-16T10:36:47.308+0000] {python.py:237} INFO - Done. Returned value was: 588
[2024-04-16T10:36:47.309+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:36:47.364+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=sum_list_number, execution_date=20240228T000000, start_date=20240416T103646, end_date=20240416T103647
[2024-04-16T10:36:47.453+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:36:47.538+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:36:47.543+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
