[2024-04-16T10:30:21.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:30:21.804+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:30:21.822+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-09T00:00:00+00:00 [queued]>
[2024-04-16T10:30:21.823+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 6
[2024-04-16T10:30:21.855+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): task_5> on 2024-04-09 00:00:00+00:00
[2024-04-16T10:30:21.880+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=376) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:30:21.887+0000] {standard_task_runner.py:63} INFO - Started process 377 to run task
[2024-04-16T10:30:21.884+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_one_dag_v1', 'task_5', 'scheduled__2024-04-09T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_one_dag.py', '--cfg-path', '/tmp/tmpt4pvf78u']
[2024-04-16T10:30:21.906+0000] {standard_task_runner.py:91} INFO - Job 270: Subtask task_5
[2024-04-16T10:30:22.250+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_one_dag_v1.task_5 scheduled__2024-04-09T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:30:39.296+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 270 for task task_5 ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 377)
[2024-04-16T10:30:52.066+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T10:30:52.237+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:30:52.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
