[2024-04-16T10:37:06.489+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T10:37:06.582+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-16T10:37:06.606+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-14T00:00:00+00:00 [queued]>
[2024-04-16T10:37:06.607+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T10:37:06.635+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_number> on 2024-03-14 00:00:00+00:00
[2024-04-16T10:37:06.648+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T10:37:06.651+0000] {standard_task_runner.py:63} INFO - Started process 567 to run task
[2024-04-16T10:37:06.652+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'priority_one_number_two_dag_v1', 'generate_random_number', 'scheduled__2024-03-14T00:00:00+00:00', '--job-id', '323', '--raw', '--subdir', 'DAGS_FOLDER/priority_one_number_two_dag.py', '--cfg-path', '/tmp/tmpahy6q5h0']
[2024-04-16T10:37:06.659+0000] {standard_task_runner.py:91} INFO - Job 323: Subtask generate_random_number
[2024-04-16T10:37:06.798+0000] {task_command.py:426} INFO - Running <TaskInstance: priority_one_number_two_dag_v1.generate_random_number scheduled__2024-03-14T00:00:00+00:00 [running]> on host eaff2d74d54d
[2024-04-16T10:37:07.125+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ika' AIRFLOW_CTX_DAG_ID='priority_one_number_two_dag_v1' AIRFLOW_CTX_TASK_ID='generate_random_number' AIRFLOW_CTX_EXECUTION_DATE='2024-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-14T00:00:00+00:00'
[2024-04-16T10:37:07.127+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T10:37:07.179+0000] {python.py:237} INFO - Done. Returned value was: [18, 5, 28, 37, 5, 7, 14, 29, 3, 3, 49, 38, 20, 38, 48, 26, 46, 41, 16, 15, 30, 34, 24, 34, 40]
[2024-04-16T10:37:07.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T10:37:07.218+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=priority_one_number_two_dag_v1, task_id=generate_random_number, execution_date=20240314T000000, start_date=20240416T103706, end_date=20240416T103707
[2024-04-16T10:37:07.281+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-16T10:37:07.397+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-16T10:37:07.438+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
